apiVersion: v1
kind: Service
metadata:
  name: cassandra
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: cassandra
  ports:
    - name: cql
      port: 9042
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
spec:
  serviceName: cassandra
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cassandra
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cassandra
    spec:
      containers:
        - name: cassandra
          image: {{ .Values.cassandra.image }}
          ports:
            - name: cql
              containerPort: 9042
          env:
            - name: CASSANDRA_CLUSTER_NAME
              value: training
          volumeMounts:
            - name: data
              mountPath: /var/lib/cassandra
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: {{ .Values.cassandra.storage }}