---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-config
  labels:
    app: services
data:
  server.port: "8080"
  server.threadPool.threads.minimum: "2"
  server.threadPool.threads.maximum: "5"
  eureka.client.registerWithEureka: "false"
  eureka.client.fetchRegistry: "false"
  ribbon.eureka.enabled: "true"
  database.cassandra.hosts: "cassandra"
  database.cassandra.port: "9042"
  database.cassandra.keySpace: "oms"
  server.log.path: "/var/log/oms"
  server.log.level: "INFO"
  JAVA_HEAP_MEMORY: "-Xms256M -Xmx512M"
  inventory.host: "inventory-svc"
  inventory.port: "80"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-config
  labels:
    app: cassandra
data:
  CASSANDRA_SEEDS: "cassandra-pods-0.cassandra.default.svc.cluster.local"
  SCHEMA_SEED_INSTANCE: "cassandra-pods-0"
  REPLICATION_FACTOR: "3"
