---
apiVersion: v1
kind: Service
metadata:
  name: inventory-svc
  labels:
    app: inventory-svc
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: inventory-svc
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-svc-pods
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-svc
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxUnavailable: 25%
       maxSurge: 1
  template:
    metadata:
      labels:
        app: inventory-svc
    spec:
      initContainers:
      - name: wait-for-cassandra
        image: cassandra
        command: [ '/bin/bash','-c', 'until echo exit | cqlsh cassandra; do echo waiting for cassandra; sleep 5; done;' ]
      containers:
      - name: inventory-svc-cont
        image: IMAGE_REGISTRY_PATH/micro-service:REVISION_ID
        args: ["inventory"]
        imagePullPolicy: IMAGE_PULL_POLICY
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: log-data
            mountPath: /var/log/oms
        envFrom:
          - configMapRef:
              name: service-config
        env:
          - name: database.type
            value: cassandra
          - name: eureka.instance.hostname
            value: inventory-svc
        livenessProbe:
          httpGet:
            path: /inventory/health
            port: 8080
          initialDelaySeconds: 180
        readinessProbe:
          httpGet:
            path: /inventory/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 2
      volumes:
        - name: log-data
          emptyDir: {}
      topologySpreadConstraints:                                                                                                                     
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: inventory-svc
